-- Insert motivational quotes into database
INSERT INTO motivational_quotes (quote, author, category, date) VALUES
('The only way to do great work is to love what you do.', 'Steve Jobs', 'PASSION', CURRENT_DATE - INTERVAL '30 days'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'COURAGE', CURRENT_DATE - INTERVAL '29 days'),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'BELIEF', CURRENT_DATE - INTERVAL '28 days'),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'CONSISTENCY', CURRENT_DATE - INTERVAL '27 days'),
('The expert in anything was once a beginner.', 'Helen Hayes', 'LEARNING', CURRENT_DATE - INTERVAL '26 days'),
('Strength does not come from physical capacity. It comes from an indomitable will.', 'Mahatma Gandhi', 'STRENGTH', CURRENT_DATE - INTERVAL '25 days'),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'ACTION', CURRENT_DATE - INTERVAL '24 days'),
('In the middle of difficulty lies opportunity.', 'Albert Einstein', 'OPPORTUNITY', CURRENT_DATE - INTERVAL '23 days'),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', 'BELIEF', CURRENT_DATE - INTERVAL '22 days'),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Anonymous', 'HARDWORK', CURRENT_DATE - INTERVAL '21 days'),
('Patience is not the ability to wait, but the ability to keep a good attitude while waiting.', 'Joyce Meyer', 'PATIENCE', CURRENT_DATE - INTERVAL '20 days'),
('The secret of getting ahead is getting started.', 'Mark Twain', 'ACTION', CURRENT_DATE - INTERVAL '19 days'),
('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'CONSISTENCY', CURRENT_DATE - INTERVAL '18 days'),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', 'BELIEF', CURRENT_DATE - INTERVAL '17 days'),
('Knowledge is power.', 'Francis Bacon', 'KNOWLEDGE', CURRENT_DATE - INTERVAL '16 days'),
('A healthy outside starts from the inside.', 'Robert Urich', 'HEALTH', CURRENT_DATE - INTERVAL '15 days'),
('The body achieves what the mind believes.', 'Napoleon Hill', 'BELIEF', CURRENT_DATE - INTERVAL '14 days'),
('Success is the sum of small efforts repeated day in and day out.', 'Robert Collier', 'CONSISTENCY', CURRENT_DATE - INTERVAL '13 days'),
('The only way to achieve the impossible is to believe it is possible.', 'Charles Kingsleigh', 'BELIEF', CURRENT_DATE - INTERVAL '12 days'),
('Champions keep playing until they get it right.', 'Billie Jean King', 'PERSEVERANCE', CURRENT_DATE - INTERVAL '11 days'),
('The pain of discipline is less than the pain of regret.', 'Jim Rohn', 'DISCIPLINE', CURRENT_DATE - INTERVAL '10 days'),
('Your body can stand almost anything. It''s your mind you have to convince.', 'Unknown', 'STRENGTH', CURRENT_DATE - INTERVAL '9 days'),
('Education is the passport to the future.', 'Malcolm X', 'KNOWLEDGE', CURRENT_DATE - INTERVAL '8 days'),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'CHOICE', CURRENT_DATE - INTERVAL '7 days'),
('Fall seven times, stand up eight.', 'Japanese Proverb', 'RESILIENCE', CURRENT_DATE - INTERVAL '6 days'),
('The journey of a thousand miles begins with one step.', 'Lao Tzu', 'ACTION', CURRENT_DATE - INTERVAL '5 days'),
('Strength grows in the moments when you think you can''t go on but you keep going anyway.', 'Unknown', 'STRENGTH', CURRENT_DATE - INTERVAL '4 days'),
('Learning never exhausts the mind.', 'Leonardo da Vinci', 'LEARNING', CURRENT_DATE - INTERVAL '3 days'),
('The difference between ordinary and extraordinary is that little extra.', 'Jimmy Johnson', 'EXTRA', CURRENT_DATE - INTERVAL '2 days'),
('Yesterday is history, tomorrow is a mystery, today is a gift.', 'Eleanor Roosevelt', 'PRESENT', CURRENT_DATE - INTERVAL '1 day'),
('Be brave enough to be bad at something new.', 'Jon Acuff', 'COURAGE', CURRENT_DATE);
